server:
  port: 9005
spring:
  application:
    name: content-service
  datasource:
    url: jdbc:mysql://localhost:3306/healthdb?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_history_content

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

minio:
  endpoint: http://minio:9000
  external-url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin


management:
  endpoints:
    web:
      exposure:
        include: health,info
